#entry types
TEXTPART = 'TEXTPART'
NEWLINE = 'NEWLINE'

#文字格式控制
ITALIC_BEGIN = 'ITALIC_BEGIN'
ITALIC_END = 'ITALIC_END'
BOLD_BEGIN = 'BOLD_BEGIN'
BOLD_END = 'BOLD_END'
BOLD_ITALIC_BEGIN = 'BOLD_ITALIC_BEGIN'
BOLD_ITALIC_END = 'BOLD_ITALIC_END'

#公式代码环境分隔符
FML_BEGIN = 'FML_BEGIN'
FML_END = 'FML_END'
MULTILINE_FML_BEGIN = 'MULTILINE_FML_BEGIN'
MULTILINE_FML_END = 'MULTILINE_FML_END'
MULTILINE_CODE_BEGIN = 'MULTILINE_CODE_BEGIN'
MULTILINE_CODE_END = 'MULTILINE_CODE_END'
CODE_BEGIN = MULTILINE_CODE_BEGIN
CODE_END = MULTILINE_CODE_END

#标题和段落控制
TITLE = 'TITLE'
SECTION = 'SECTION'
SUBSECTION = 'SUBSECTION'
SUBSUBSECTION = 'SUBSUBSECTION'

#单行的分隔符
DELIM = 'DELIM'

#枚举环境
ENUM_BEGIN = 'ENUM_BEGIN'
ENUM_END = 'ENUM_END'
ITEM = 'ITEM'

IMAGE = 'IMAGE'